import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadPredictionPDF = (prediction) => {

    const doc = new jsPDF();

    // ==========================================
    // Header
    // ==========================================

    doc.setFontSize(22);

    doc.setTextColor(39, 104, 57);

    doc.text(

        "AgriMind",

        15,

        18

    );

    doc.setFontSize(12);

    doc.setTextColor(120);

    doc.text(

        "Crop Recommendation Report",

        15,

        26

    );

    doc.line(

        15,

        30,

        195,

        30

    );

    // ==========================================
    // Crop
    // ==========================================

    doc.setFontSize(18);

    doc.setTextColor(0);

    doc.text(

        `Recommended Crop: ${prediction.recommended_crop}`,

        15,

        42

    );

    doc.setFontSize(13);

    doc.text(

        `Confidence : ${prediction.confidence}%`,

        15,

        52

    );

    doc.text(

        `Season : ${prediction.season}`,

        15,

        60

    );

    doc.text(

        `Location : ${prediction.location || "-"}`,

        15,

        68

    );

    // ==========================================
    // Soil Data
    // ==========================================

    autoTable(doc, {

        startY: 78,

        head: [

            [

                "Parameter",

                "Value",

            ],

        ],

        body: [

            [

                "Nitrogen",

                prediction.nitrogen,

            ],

            [

                "Phosphorus",

                prediction.phosphorus,

            ],

            [

                "Potassium",

                prediction.potassium,

            ],

            [

                "Temperature",

                `${prediction.temperature} °C`,

            ],

            [

                "Humidity",

                `${prediction.humidity}%`,

            ],

            [

                "Rainfall",

                `${prediction.rainfall} mm`,

            ],

            [

                "pH",

                prediction.ph,

            ],

            [

                "Moisture",

                `${prediction.soil_moisture}%`,

            ],

            [

                "Organic Carbon",

                prediction.organic_carbon,

            ],

            [

                "Electrical Conductivity",

                prediction.electrical_conductivity,

            ],

        ],

    });

    // ==========================================
    // Top Recommendations
    // ==========================================

    autoTable(doc, {

        startY:

            doc.lastAutoTable.finalY + 10,

        head: [

            [

                "Top Crop",

                "Probability",

            ],

        ],

        body:

            prediction.top_recommendations.map(

                (item) => [

                    item.crop,

                    `${item.probability}%`,

                ]

            ),

    });

    // ==========================================
    // Farming
    // ==========================================

    autoTable(doc, {

        startY:

            doc.lastAutoTable.finalY + 10,

        head: [

            [

                "Farm Information",

                "Value",

            ],

        ],

        body: [

            [

                "Area",

                `${prediction.area || 0} Acres`,

            ],

            [

                "Investment",

                `₹${prediction.investment || 0}`,

            ],

            [

                "Revenue",

                prediction.revenue == null

                    ? "--"

                    : `₹${prediction.revenue}`,

            ],

            [

                "Profit",

                prediction.profit == null

                    ? "--"

                    : `₹${prediction.profit}`,

            ],

            [

                "Status",

                prediction.status,

            ],

        ],

    });

    // ==========================================
    // Footer
    // ==========================================

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(

        `Generated on ${new Date().toLocaleDateString("en-IN")}`,

        15,

        285

    );

    doc.text(

        "Generated by AgriMind",

        145,

        285

    );

    doc.save(

        `${prediction.recommended_crop}_Report.pdf`

    );

};